apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-mongo-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/pranavnandane/Desktop/healthcare/auth-mongo-data # Change YOUR_USERNAME to your macOS username
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: '' # Set to empty string or remove this line
  volumeName: auth-mongo-pv # Reference the PV here
