apiVersion: v1
kind: PersistentVolume
metadata:
  name: doctor-mysql-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/pranavnandane/Desktop/healthcare/doctor-mysql-data # Change YOUR_USERNAME to your macOS username
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: doctor-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: '' # Set to empty string or remove this line
  volumeName: doctor-mysql-pv # Reference the PV here
