apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-mysql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatsapp-mysql
  template:
    metadata:
      labels:
        app: whatsapp-mysql
    spec:
      containers:
        - name: whatsapp-mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 'Pranav@2448'
            - name: MYSQL_DATABASE
              value: 'healthcare'
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: whatsapp-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: whatsapp-mysql-srv
spec:
  selector:
    app: whatsapp-mysql
  ports:
    - name: db
      protocol: TCP
      port: 3306
      targetPort: 3306
