apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatsapp
  template:
    metadata:
      labels:
        app: whatsapp
    spec:
      containers:
        - name: whatsapp # this name is only important for logging purposes
          image: oopdaddy/whatsapp
          #          image: us.gcr.io/ticketing-dev-425001/whatsapp
          env:
            #            - name: JWT_KEY # this is the name viz we are able to get in the whatsapp service
            #              valueFrom:
            #                secretKeyRef:
            #                  name: jwt-secret
            #                  key: jwt
            - name: MYSQL_ROOT_PASSWORD
              value: 'Pranav@2448'
            - name: MYSQL_DATABASE
              value: 'healthcare'
            - name: MYSQL_USER
              value: 'root'
            - name: MYSQL_HOST
              value: 'whatsapp-mysql-srv'
            - name: MYSQL_PORT
              value: '3306'
            - name: WEBHOOK_VERIFY_TOKEN
              value: 'Pranav@2448'
            - name: WHATSAPP_PHONE_NUMBER_ID
              value: '227707410434620'
            - name: WHATSAPP_ACCESS_TOKEN
              value: 'EAAF2DM2fAtUBO9hpS4pTXu3yFOOOaiSrbZCqv1mzGJSqtmn2aIqCQzjj1K71LJqZBBvGmDRjLvev9RsghZAlezUTl8wx3LKe83NH4b0Xlw4iakUAeiqY7Q5hZC8jkCumNz4DDDn8WVJRE9xYc9BrWJEHMoDMWlSo0V1vXyjh09NAANDQaaC4c7qBj58EXMfIjAZDZD'
            - name: PINECONE_API_KEY # this is the name viz we are able to get in the whatsapp service
              valueFrom:
                secretKeyRef:
                  name: pinecone-apikey
                  key: PINECONE_API_KEY
            - name: OPENAI_API_KEY # this is the name viz we are able to get in the whatsapp service
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: OPENAI_API_KEY
            - name: DEEPSEEK_API_KEY # this is the name viz we are able to get in the whatsapp service
              valueFrom:
                secretKeyRef:
                  name: deepseek-secret
                  key: DEEPSEEK_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: whatsapp-srv
spec:
  selector:
    app: whatsapp
  ports:
    - name: whatsapp
      protocol: TCP
      port: 3000
      targetPort: 3000
